# Site settings
title:       le site de sidbhatt11
email:       sidbhatt11@yahoo.in
author:      Siddharth Bhatt
description: "LOL, what ?"
baseurl:     ""
url:         "http://127.0.0.1:4000"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: sidbhatt11
bitbucket_username: sidbhatt11
stackoverflow_id:
twitter_username: sidbhatt11
google_plus_id:
linkedin_username: sidbhatt11
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
gems: [jekyll-paginate]
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
